[package]
name = "r2r_pub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.colcon]
inherits = "release"

[dependencies]
r2r = "0.8.3"
tokio = { version = "1.36.0", features = ["full"] }
